# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :forwarded_port, guest: 3000, host: 3000 

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "init.pp"
    puppet.module_path    = "puppet/modules"
  end

  config.vm.provider :virtualbox do |vb|
    # Boot with headless mode
    vb.gui = false

    # Set memory:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  
end
